# YAML configuration file used to connect each widget to its model.
# The data structure will be a dictionary compose by lists of
# the following elements:

#  -------------------------------------------------------
# |                      attributes                       |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      readback                         |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      comboboxes                       |
#  -------------------------------------------------------
# | widget_name | tango_attribute | values_for_comboboxes |
#  -------------------------------------------------------

attributes:
- [taurusWheelEdit, ItckNumber]

readback:
# Cavity A
- [TaurusLed, Diag_Rvtet1A]
- [TaurusLed_2, Diag_Rvtet2A]
- [TaurusLed_3, Diag_RvcircA]
- [TaurusLed_4, Diag_FwloadA]
- [TaurusLed_5, Diag_FwhybloadA]
- [TaurusLed_6, Diag_RvcavA]
- [TaurusLed_7, Diag_ManualInterlockA]
- [TaurusLed_8, Diag_ArcsA]
- [TaurusLed_9, Diag_VacuumA]
- [TaurusLed_10, Diag_ExternalItckA]
- [TaurusLed_41, Diag_PlungerEndSwitchUpA]
- [TaurusLed_43, Diag_PlungerEndSwitchDownA]
# Cavity A
- [TaurusLed_11, Diag_Rvtet1B]
- [TaurusLed_12, Diag_Rvtet2B]
- [TaurusLed_13, Diag_RvcircB]
- [TaurusLed_14, Diag_FwloadB]
- [TaurusLed_15, Diag_FwhybloadB]
- [TaurusLed_16, Diag_RvcavB]
- [TaurusLed_17, Diag_ManualInterlockB]
- [TaurusLed_18, Diag_ArcsB]
- [TaurusLed_19, Diag_VacuumB]
- [TaurusLed_20, Diag_ExternalItckB]
- [TaurusLed_42, Diag_PlungerEndSwitchUpB]
- [TaurusLed_44, Diag_PlungerEndSwitchDownB]

comboboxes:
-
