# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OVRDiag.ui'
#
# Created by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(493, 261)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self._22 = QtGui.QGridLayout()
        self._22.setSpacing(0)
        self._22.setObjectName(_fromUtf8("_22"))
        self.label_152 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_152.sizePolicy().hasHeightForWidth())
        self.label_152.setSizePolicy(sizePolicy)
        self.label_152.setMinimumSize(QtCore.QSize(100, 20))
        self.label_152.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_152.setFont(font)
        self.label_152.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self._22.addWidget(self.label_152, 0, 0, 1, 1)
        self.taurusBoolLed = TaurusBoolLed(Form)
        self.taurusBoolLed.setObjectName(_fromUtf8("taurusBoolLed"))
        self._22.addWidget(self.taurusBoolLed, 0, 1, 1, 1)
        self.label_153 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_153.sizePolicy().hasHeightForWidth())
        self.label_153.setSizePolicy(sizePolicy)
        self.label_153.setMinimumSize(QtCore.QSize(100, 20))
        self.label_153.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_153.setFont(font)
        self.label_153.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_153.setObjectName(_fromUtf8("label_153"))
        self._22.addWidget(self.label_153, 1, 0, 1, 1)
        self.taurusBoolLed_2 = TaurusBoolLed(Form)
        self.taurusBoolLed_2.setObjectName(_fromUtf8("taurusBoolLed_2"))
        self._22.addWidget(self.taurusBoolLed_2, 1, 1, 1, 1)
        self.label_147 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_147.sizePolicy().hasHeightForWidth())
        self.label_147.setSizePolicy(sizePolicy)
        self.label_147.setMinimumSize(QtCore.QSize(100, 20))
        self.label_147.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_147.setFont(font)
        self.label_147.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self._22.addWidget(self.label_147, 2, 0, 1, 1)
        self.taurusBoolLed_3 = TaurusBoolLed(Form)
        self.taurusBoolLed_3.setObjectName(_fromUtf8("taurusBoolLed_3"))
        self._22.addWidget(self.taurusBoolLed_3, 2, 1, 1, 1)
        self.label_148 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_148.sizePolicy().hasHeightForWidth())
        self.label_148.setSizePolicy(sizePolicy)
        self.label_148.setMinimumSize(QtCore.QSize(100, 20))
        self.label_148.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_148.setFont(font)
        self.label_148.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_148.setObjectName(_fromUtf8("label_148"))
        self._22.addWidget(self.label_148, 3, 0, 1, 1)
        self.taurusBoolLed_4 = TaurusBoolLed(Form)
        self.taurusBoolLed_4.setObjectName(_fromUtf8("taurusBoolLed_4"))
        self._22.addWidget(self.taurusBoolLed_4, 3, 1, 1, 1)
        self.label_149 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_149.sizePolicy().hasHeightForWidth())
        self.label_149.setSizePolicy(sizePolicy)
        self.label_149.setMinimumSize(QtCore.QSize(100, 20))
        self.label_149.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_149.setFont(font)
        self.label_149.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_149.setObjectName(_fromUtf8("label_149"))
        self._22.addWidget(self.label_149, 4, 0, 1, 1)
        self.taurusBoolLed_5 = TaurusBoolLed(Form)
        self.taurusBoolLed_5.setObjectName(_fromUtf8("taurusBoolLed_5"))
        self._22.addWidget(self.taurusBoolLed_5, 4, 1, 1, 1)
        self.label_150 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_150.sizePolicy().hasHeightForWidth())
        self.label_150.setSizePolicy(sizePolicy)
        self.label_150.setMinimumSize(QtCore.QSize(110, 20))
        self.label_150.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_150.setFont(font)
        self.label_150.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self._22.addWidget(self.label_150, 5, 0, 1, 1)
        self.taurusBoolLed_6 = TaurusBoolLed(Form)
        self.taurusBoolLed_6.setObjectName(_fromUtf8("taurusBoolLed_6"))
        self._22.addWidget(self.taurusBoolLed_6, 5, 1, 1, 1)
        self.label_156 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_156.sizePolicy().hasHeightForWidth())
        self.label_156.setSizePolicy(sizePolicy)
        self.label_156.setMinimumSize(QtCore.QSize(100, 20))
        self.label_156.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_156.setFont(font)
        self.label_156.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_156.setObjectName(_fromUtf8("label_156"))
        self._22.addWidget(self.label_156, 7, 0, 1, 1)
        self.taurusBoolLed_8 = TaurusBoolLed(Form)
        self.taurusBoolLed_8.setObjectName(_fromUtf8("taurusBoolLed_8"))
        self._22.addWidget(self.taurusBoolLed_8, 7, 1, 1, 1)
        self.label_142 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_142.sizePolicy().hasHeightForWidth())
        self.label_142.setSizePolicy(sizePolicy)
        self.label_142.setMinimumSize(QtCore.QSize(100, 20))
        self.label_142.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_142.setFont(font)
        self.label_142.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_142.setObjectName(_fromUtf8("label_142"))
        self._22.addWidget(self.label_142, 6, 0, 1, 1)
        self.taurusBoolLed_7 = TaurusBoolLed(Form)
        self.taurusBoolLed_7.setObjectName(_fromUtf8("taurusBoolLed_7"))
        self._22.addWidget(self.taurusBoolLed_7, 6, 1, 1, 1)
        self.gridLayout.addLayout(self._22, 0, 0, 1, 1)
        self._23 = QtGui.QGridLayout()
        self._23.setSpacing(0)
        self._23.setObjectName(_fromUtf8("_23"))
        self.label_154 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_154.sizePolicy().hasHeightForWidth())
        self.label_154.setSizePolicy(sizePolicy)
        self.label_154.setMinimumSize(QtCore.QSize(100, 20))
        self.label_154.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_154.setFont(font)
        self.label_154.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_154.setObjectName(_fromUtf8("label_154"))
        self._23.addWidget(self.label_154, 0, 0, 1, 1)
        self.taurusBoolLed_9 = TaurusBoolLed(Form)
        self.taurusBoolLed_9.setObjectName(_fromUtf8("taurusBoolLed_9"))
        self._23.addWidget(self.taurusBoolLed_9, 0, 1, 1, 1)
        self.label_155 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_155.sizePolicy().hasHeightForWidth())
        self.label_155.setSizePolicy(sizePolicy)
        self.label_155.setMinimumSize(QtCore.QSize(100, 20))
        self.label_155.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_155.setFont(font)
        self.label_155.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self._23.addWidget(self.label_155, 1, 0, 1, 1)
        self.taurusBoolLed_10 = TaurusBoolLed(Form)
        self.taurusBoolLed_10.setObjectName(_fromUtf8("taurusBoolLed_10"))
        self._23.addWidget(self.taurusBoolLed_10, 1, 1, 1, 1)
        self.label_151 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_151.sizePolicy().hasHeightForWidth())
        self.label_151.setSizePolicy(sizePolicy)
        self.label_151.setMinimumSize(QtCore.QSize(100, 20))
        self.label_151.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_151.setFont(font)
        self.label_151.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self._23.addWidget(self.label_151, 2, 0, 1, 1)
        self.taurusBoolLed_11 = TaurusBoolLed(Form)
        self.taurusBoolLed_11.setObjectName(_fromUtf8("taurusBoolLed_11"))
        self._23.addWidget(self.taurusBoolLed_11, 2, 1, 1, 1)
        self.label_157 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_157.sizePolicy().hasHeightForWidth())
        self.label_157.setSizePolicy(sizePolicy)
        self.label_157.setMinimumSize(QtCore.QSize(100, 20))
        self.label_157.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_157.setFont(font)
        self.label_157.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_157.setObjectName(_fromUtf8("label_157"))
        self._23.addWidget(self.label_157, 3, 0, 1, 1)
        self.taurusBoolLed_12 = TaurusBoolLed(Form)
        self.taurusBoolLed_12.setObjectName(_fromUtf8("taurusBoolLed_12"))
        self._23.addWidget(self.taurusBoolLed_12, 3, 1, 1, 1)
        self.label_158 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_158.sizePolicy().hasHeightForWidth())
        self.label_158.setSizePolicy(sizePolicy)
        self.label_158.setMinimumSize(QtCore.QSize(100, 20))
        self.label_158.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_158.setFont(font)
        self.label_158.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_158.setObjectName(_fromUtf8("label_158"))
        self._23.addWidget(self.label_158, 4, 0, 1, 1)
        self.taurusBoolLed_13 = TaurusBoolLed(Form)
        self.taurusBoolLed_13.setObjectName(_fromUtf8("taurusBoolLed_13"))
        self._23.addWidget(self.taurusBoolLed_13, 4, 1, 1, 1)
        self.label_159 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_159.sizePolicy().hasHeightForWidth())
        self.label_159.setSizePolicy(sizePolicy)
        self.label_159.setMinimumSize(QtCore.QSize(120, 20))
        self.label_159.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_159.setFont(font)
        self.label_159.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_159.setObjectName(_fromUtf8("label_159"))
        self._23.addWidget(self.label_159, 5, 0, 1, 1)
        self.taurusBoolLed_14 = TaurusBoolLed(Form)
        self.taurusBoolLed_14.setObjectName(_fromUtf8("taurusBoolLed_14"))
        self._23.addWidget(self.taurusBoolLed_14, 5, 1, 1, 1)
        self.label_160 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_160.sizePolicy().hasHeightForWidth())
        self.label_160.setSizePolicy(sizePolicy)
        self.label_160.setMinimumSize(QtCore.QSize(100, 20))
        self.label_160.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_160.setFont(font)
        self.label_160.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_160.setObjectName(_fromUtf8("label_160"))
        self._23.addWidget(self.label_160, 7, 0, 1, 1)
        self.taurusBoolLed_15 = TaurusBoolLed(Form)
        self.taurusBoolLed_15.setObjectName(_fromUtf8("taurusBoolLed_15"))
        self._23.addWidget(self.taurusBoolLed_15, 7, 1, 1, 1)
        self.label_143 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_143.sizePolicy().hasHeightForWidth())
        self.label_143.setSizePolicy(sizePolicy)
        self.label_143.setMinimumSize(QtCore.QSize(100, 20))
        self.label_143.setMaximumSize(QtCore.QSize(93, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_143.setFont(font)
        self.label_143.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_143.setObjectName(_fromUtf8("label_143"))
        self._23.addWidget(self.label_143, 6, 0, 1, 1)
        self.taurusBoolLed_16 = TaurusBoolLed(Form)
        self.taurusBoolLed_16.setObjectName(_fromUtf8("taurusBoolLed_16"))
        self._23.addWidget(self.taurusBoolLed_16, 6, 1, 1, 1)
        self.gridLayout.addLayout(self._23, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_152.setText(QtGui.QApplication.translate("Form", "ADC1: RvTet1A", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_153.setText(QtGui.QApplication.translate("Form", "ADC2: RvTet2A", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_2.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_2.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_147.setText(QtGui.QApplication.translate("Form", "ADC3: FwCircA", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_3.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_3.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_148.setText(QtGui.QApplication.translate("Form", "ADC4: RvCircA", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_4.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_4.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_149.setText(QtGui.QApplication.translate("Form", "ADC5: FwLoadA", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_5.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_5.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_150.setText(QtGui.QApplication.translate("Form", "ADC6: FwHybLoadA", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_6.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_6.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_156.setText(QtGui.QApplication.translate("Form", "ADC8: MO", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_8.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_8.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_142.setText(QtGui.QApplication.translate("Form", "ADC7: RvCavA", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_7.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_7.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_154.setText(QtGui.QApplication.translate("Form", "ADC9: RvTet1B", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_9.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_9.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_155.setText(QtGui.QApplication.translate("Form", "ADC10: RvTet2B", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_10.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_10.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_151.setText(QtGui.QApplication.translate("Form", "ADC11: FwCircB", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_11.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_11.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_157.setText(QtGui.QApplication.translate("Form", "ADC12: RvCircB", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_12.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_12.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_158.setText(QtGui.QApplication.translate("Form", "ADC13: FwLoadB", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_13.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_13.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_159.setText(QtGui.QApplication.translate("Form", "ADC14: FwHybLoadB", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_14.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_14.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_160.setText(QtGui.QApplication.translate("Form", "ADC16: Landau", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_15.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_15.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_143.setText(QtGui.QApplication.translate("Form", "ADC15: RvCavB", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_16.setProperty(_fromUtf8("ledColor"), QtGui.QApplication.translate("Form", "RED", None, QtGui.QApplication.UnicodeUTF8))
        self.taurusBoolLed_16.setProperty(_fromUtf8("ledColorOff"), QtGui.QApplication.translate("Form", "REDOFF", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusBoolLed

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

