# YAML configuration file used to connect each widget to its model.
# The data structure will be a dictionary compose by lists of
# the following elements:

#  -------------------------------------------------------
# |                      attributes                       |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      readback                         |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      comboboxes                       |
#  -------------------------------------------------------
# | widget_name | tango_attribute | values_for_comboboxes |
#  -------------------------------------------------------

attributes:
-

readback:
# Cavity A
- [tauValueLabel_rTuningD, Diag_AngCavFwA]
- [tauValueLabel_rFwAmp, Diag_AngFwLA]
- [tauValueLabel_rCavVolt, Diag_AngCavLA]
# Cavity B
- [tauValueLabel_rTuningD_2, Diag_AngCavFwB]
- [tauValueLabel_rFwAmp_2, Diag_AngFwLB]
- [tauValueLabel_rCavVolt_2, Diag_AngCavLB]

comboboxes:
-
