# YAML configuration file used to connect each widget to its model.
# The data structure will be a dictionary compose by lists of
# the following elements:

#  -------------------------------------------------------
# |                      attributes                       |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      readback                         |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      comboboxes                       |
#  -------------------------------------------------------
# | widget_name | tango_attribute | values_for_comboboxes |
#  -------------------------------------------------------

attributes:
-

readback:
# Cavity A
- [TaurusLed_21, Diag_DacsDisableCommandA]
- [TaurusLed_22, Diag_PinSwitchA]
- [TaurusLed_45, Diag_FdlTriggerToLoopsdiagboardA]
- [TaurusLed_47, Diag_OutputToPlcA]
- [TaurusLed_48, Diag_OutputToMpsA]

# Cavity B
- [TaurusLed_49, Diag_DacsDisableCommandB]
- [TaurusLed_50, Diag_PinSwitchB]
- [TaurusLed_51, Diag_FdlTriggerToLoopsdiagboardB]
- [TaurusLed_53, Diag_OutputToPlcB]
- [TaurusLed_54, Diag_OutputToMpsB]

comboboxes:
-
