# YAML configuration file used to connect each widget to its model.
# The data structure will be a dictionary compose by lists of
# the following elements:

#  -------------------------------------------------------------------------
# |                               attributes                                |
#  -------------------------------------------------------------------------
# |    widget_name    |    tango_attribute    |    use_diagnostic_device    |
#  -------------------------------------------------------------------------

#  -------------------------------------------------------------------------
# |                                readback                                 |
#  -------------------------------------------------------------------------
# |    widget_name    |    tango_attribute    |    use_diagnostic_device    |
#  -------------------------------------------------------------------------

#  -------------------------------------------------------------------------
# |                               comboboxes                                |
#  -------------------------------------------------------------------------
# | widget_name | tango_attribute | values_for_comboboxes | use_diag_device |
#  -------------------------------------------------------------------------


attributes:
-

readback:
# Cavity A
- [lyrtechStatus1, state, false]
- [lyrtechStatus2, state, true]

comboboxes:
-
