# YAML configuration file used to connect each widget to its model.
# The data structure will be a dictionary compose by lists of
# the following elements:

#  -------------------------------------------------------
# |                      attributes                       |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      readback                         |
#  -------------------------------------------------------
# |              widget_name | tango_attribute            |
#  -------------------------------------------------------

#  -------------------------------------------------------
# |                      comboboxes                       |
#  -------------------------------------------------------
# | widget_name | tango_attribute | values_for_comboboxes |
#  -------------------------------------------------------

attributes:
# Cavity A
- [lineEdit_numberPulses_3, NumstepsA]
- [lineEdit_tuningOffset_3, LandauphaseoffsetA]
- [lineEdit_marginUp_4, LandaumarginupA]
- [lineEdit_marginLow_4, LandaumarginlowA]
- [lineEdit_landauAmpSet, LandauampsettingA]
- [lineEdit_forwardMin_4, MinimumLandauAmplitudeA]

# Cavity B
- [lineEdit_numberPulses_4, NumstepsB]
- [lineEdit_tuningOffset_4, LandauphaseoffsetB]
- [lineEdit_marginUp_5, LandaumarginupB]
- [lineEdit_marginLow_5, LandaumarginlowB]
- [lineEdit_landauAmpSet_2, LandauampsettingB]
- [lineEdit_forwardMin_5, MinimumLandauAmplitudeB]

readback:
# Cavity A
- [taurusBoolLed_37, Diag_PlungerMovingManualTuningA]
- [taurusBoolLed_38, Diag_PlungerMovingUpManualTuningA]
- [tauValueLabel_numberPulses_4, NumStepsA]
- [tauValueLabel_moveUp_3, MovelandauupA]
- [tauValueLabel_movePlg1_3, MovelandauplgA]

- [taurusBoolLed_39, Diag_PlungerMovingAutomaticTuningA]
- [taurusBoolLed_40, Diag_PlungerMovingUpAutomaticTuningA]
- [tauValueLabel_tuningOffset_3, LandauphaseoffsetA]
- [tauValueLabel_marginUp_3, LandaumarginupA]
- [tauValueLabel_marginLow_3, LandauMarginLowA]
- [tauValueLabel_landauAmpSet, LandauampsettingA]
- [tauValueLabel_forwardMin_5, MinimumLandauAmplitudeA]
- [tauValueLabel_tuningEn_3, LandautuningenableA]
- [tauValueLabel_tuningPosEn_3, LandauPositiveEnableA]
- [tauValueLabel_tuningEn_5, Landau3gevRingEnableA]
- [tauValueLabel_tuningPosEn_5, LandauCavEnableA]

# Cavity B
- [taurusBoolLed_41, Diag_PlungerMovingManualTuningB]
- [taurusBoolLed_42, Diag_PlungerMovingUpManualTuningB]
- [tauValueLabel_numberPulses_5, NumStepsB]
- [tauValueLabel_moveUp_4, MovelandauupB]
- [tauValueLabel_movePlg1_4, MovelandauplgB]

- [taurusBoolLed_44, Diag_PlungerMovingAutomaticTuningB]
- [taurusBoolLed_43, Diag_PlungerMovingUpAutomaticTuningB]
- [tauValueLabel_tuningOffset_4, LandauphaseoffsetB]
- [tauValueLabel_marginUp_4, LandaumarginupB]
- [tauValueLabel_marginLow_4, LandauMarginLowB]
- [tauValueLabel_landauAmpSet_2, LandauampsettingB]
- [tauValueLabel_forwardMin_6, MinimumLandauAmplitudeB]
- [tauValueLabel_tuningEn_4, LandautuningenableB]
- [tauValueLabel_tuningPosEn_4, LandauPositiveEnableB]
- [tauValueLabel_tuningEn_6, Landau3gevRingEnableB]
- [tauValueLabel_tuningPosEn_6, LandauCavEnableB]

comboboxes:
# Cavity A
- [comboBox_moveUp_3, MovelandauupA, CB]
- [comboBox_movePlg_3, MovelandauplgA, CB]
- [comboBox_tuningEn_3, LandautuningenableA, CB]
- [comboBox_tuningPosEn_3, LandauPositiveEnableA, CB]
- [comboBox_tuningEn_5, Landau3gevRingEnableA, CB]
- [comboBox_tuningPosEn_5, LandauCavEnableA, CB]

# Cavity B
- [comboBox_moveUp_4, MovelandauupB, CB]
- [comboBox_movePlg_4, MovelandauplgB, CB]
- [comboBox_tuningEn_4, LandautuningenableB, CB]
- [comboBox_tuningPosEn_4, LandauPositiveEnableB, CB]
- [comboBox_tuningEn_6, Landau3gevRingEnableB, CB]
- [comboBox_tuningPosEn_6, LandauCavEnableB, CB]
